sudo: false
language: node_js
node_js:
  - '10'
services:
  - mysql
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
install:
  - npm run install-all
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - npm run migrate-travis
script:
  - npm run validate
env:
  global:
    - NODE_ENV=travis
    - DB_DB=test
    - KEYGRIP_SECRETS="secret1 test2 aha3"
    - MIGRATION_PASS="undefined"
    - SENDGRID="NotUsed"
    - DB_USER="root"
    - DB_HOST="127.0.0.1"
