name: 'Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm run install-all

  test:
    name: Test
    needs: install
    services:
      mysql:
        image: mysql:latest
        ports:
          - '8888:3306'
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_USER: root
      DB_PASS: password
      DB_HOST: 127.0.0.1
      DB_DB: test
      DB_PORT: 8888
      NODE_ENV: github
      KEYGRIP_SECRETS: secret1 test2 aha3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test;'
      - run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';"
      - run: cd server && npm i knex && npx knex migrate:latest --env github
      - run: npm run validate

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm run build
