name: 'Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm run install-all

  test:
    name: Test
    needs: install
    services:
      mysql:
        image: mysql:8.0
        ports:
          - '8888:3306'
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: test
    env:
      DB_USER: root
      DB_PASS: rootpass
      DB_HOST: '127.0.0.1'
      DB_DB: test
      DB_PORT: 8888
      NODE_ENV: github
      KEYGRIP_SECRETS: secret1 test2 aha3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: sudo mysql -h 127.0.0.1 --port 8888 -u root -prootpass -e 'CREATE DATABASE IF NOT EXISTS test; ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'rootpass';'
      - run: cd server && npm i knex && npx knex migrate:latest --env github
      - run: npm run validate

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm run build
